### ISSUE TITLE
Could not install in kotlin multiplatform project via cocoapods

### ISSUE THREAD

**Issue by omkar-tenkale** [razorpay/razorpay-customui-pod#23]
When I try to add this library to my kotlin multiplatform project,  XCode build fails with error

```

    cocoapods {
        version = "1.0"
        summary = "Some description for a Kotlin/Native module"
        homepage = "Link to a Kotlin/Native module homepage"

        ios.deploymentTarget = "15.0"
        name = "MyCocoaPod"

        pod("razorpay-customui-pod"){
            version = "2.0.13"
            moduleName = "Razorpay"
            extraOpts += listOf("-compiler-option", "-fmodules") //refer https://kotlinlang.org/docs/native-cocoapods-libraries.html#with-custom-cinterop-options
        }

//        pod("razorpay-pod"){
//            version = "1.3.8"
//            moduleName = "Razorpay"
//            extraOpts += listOf("-compiler-option", "-fmodules") //refer https://kotlinlang.org/docs/native-cocoapods-libraries.html#with-custom-cinterop-options
//        }
    }
```

Error:
```

> Task :composeApp:cinteropRazorpayIosSimulatorArm64 FAILED

Exception in thread "main" java.lang.Error: /Users/omkar/Documents/.../zave-penny-app/composeApp/build/cocoapods/synthetic/ios/build/Release-iphonesimulator/XCFrameworkIntermediates/razorpay-customui-pod/Razorpay.framework/Headers/Razorpay-Swift.h:398:2: error: unsupported Swift architecture

	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesASTFiles(ModuleSupport.kt:80)

	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesInfo(ModuleSupport.kt:15)

	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.buildNativeLibrary(main.kt:564)

	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:307)

	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLibSafe(main.kt:243)

	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.access$processCLibSafe(main.kt:1)

	at org.jetbrains.kotlin.native.interop.gen.jvm.Interop.interop(main.kt:101)

	at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:47)

	at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:23)

	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:45)



FAILURE: Build failed with an exception.



* What went wrong:

Execution failed for task ':composeApp:cinteropRazorpayIosSimulatorArm64'.

> Process 'command '/Users/omkar/Library/Java/JavaVirtualMachines/corretto-21.0.2/Contents/Home/bin/java'' finished with non-zero exit value 1

```

**Comment by omkar-tenkale** [comment]
Commenting out both "razorpay-pod" and "razorpay-customui-pod" blocks allows the build to succeed. However, I aim to use only the "razorpay-customui-pod" block.
